
.386
DATA	SEGMENT  USE16	PUBLIC 'DATA'
DIZHI  DW  ?,?
DIZHI2 DW  ?,?

DATA ENDS 
;----------------------------------
STACK	SEGMENT  USE16 STACK
	DB	200 DUP(0)
STACK	ENDS
;----------------------------------
CODE	SEGMENT  USE16	PUBLIC 'CODE'
	ASSUME CS:CODE,DS:DATA,SS:STACK
START:  MOV AX,DATA
				MOV DS,AX
 				
 				MOV AX,3510H
 				INT 21H
 				MOV DIZHI,BX
 				MOV DIZHI+2,ES
 				
 				MOV DX,FS:[40H]
 				MOV SI,FS:[42H]
 				MOV DIZHI2,DX
 				MOV DIZHI2+2,SI
 				
 				INT 10H

				MOV AH,4CH
				INT 21H
CODE	ENDS
	END START