.386
STACK  SEGMENT  USE16  STACK
       DB  200  DUP (0)
STACK  ENDS

DATA	SEGMENT  USE16
OLD_INT DW ?, ?
DATA ENDS 

CODE   SEGMENT USE16
       ASSUME CS:CODE, DS:DATA, SS:STACK
START:	MOV AX, DATA
				MOV	DS, AX
				MOV	AX, 3508H
				INT 21H
				MOV	AX, ES:[0H]
				MOV	OLD_INT, AX
				MOV	AX, ES:[2H]
				MOV	OLD_INT+2, AX
				LDS	DX, DWORD PTR OLD_INT
				MOV	AX, 2508H
				INT 21H
				MOV	AH, 4CH
				INT	21H
CODE    ENDS
        END  START